### ISSUE TITLE
x86 config

### ISSUE THREAD

**Issue by mmcloughlin** [rems-project/isla#76]
In https://github.com/rems-project/isla/issues/75#issuecomment-1847122951 you suggested that you've had some success using ISLA with the x86 model.

I have used `isla-sail` to get `x86.ir` from `sail-x86-from-acl2`.

Do you have a `config/x86.toml` somewhere? Or can you advise on how I might create one?

Thanks!

**Comment by mmcloughlin** [comment]
I've been hacking around but it's clearly not doing the right thing yet.

My `x86.toml` is as follows. A bunch of this is copied from `plain.toml` and almost certainly wrong, like `ifetch`.

```toml
pc = "rip"

ifetch = "Read_ifetch"

read_exclusives = []
write_exclusives = []

[[toolchain]]
name = "default"
assembler = "as"
objdump = "objdump"
nm = "nm"
linker = "ld"

[mmu]
page_table_base = "0x300000"
page_size = "4096"
s2_page_table_base = "0x300000"
s2_page_size = "4096"

# This section contains the base address for loading the code for each
# thread in a litmus test, and the stride which is the distance
# between each thread in bytes. The overall range for thread memory is
# the half-open range [base,top)"
[threads]
base = "0x400000"
top = "0x500000"
stride = "0x10000"

[symbolic_addrs]
base = "0x600000"
top = "0x600000"
stride = "0x10"

[registers]
ignore = []

[registers.defaults]

# A map from register names in the litmus to Sail register specifiers
# (roughtly corresponding to l-expressions in Sail, i.e. subscripting
# R[n] and field accesses R.field are allowed.)
[registers.renames]

[reads]

[writes]

[cache_ops]
```

I can run:

```
./isla/target/debug/isla-footprint --arch sail-x86-from-acl2/model/x86.ir --config isla/configs/x86.toml -i 'and $0x1,%al' --function main -s
```

It appears to start doing something. But I'm guessing at a minimum I need a version of `isla_main.sail` for the x86 model.

Any help appreciated!
